"""add document embeddings table

Revision ID: be7ff70bc1c3
Revises: 5fa8c298a696
Create Date: 2026-06-08 00:31:27.765647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'be7ff70bc1c3'
down_revision: Union[str, Sequence[str], None] = '5fa8c298a696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(1536),  nullable=True),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_id'), 'document_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_embeddings_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    # ### end Alembic commands ###
